config/routes.rb
ActiveInboxTranslator::Application.routes.draw do

  match 'messages/:lang' => 'messages#create', :via => 'post', :as => 'messages'
  match 'messages/:lang/:id' => 'messages#update', :via => 'put', :as => 'messages'
  match 'messages(/:lang)' => 'messages#index', :via => 'get', :as => 'messages'

  match 'pages/:lang/:id/edit' => 'page#edit', :via => 'get', :as => 'page_form'
  match 'pages/:lang/:id' => 'page#update', :via => 'put', :as => 'page_update'
  match 'pages(/:lang)' => 'page#index', :via => 'get', :as => 'pages'

  get "login" => "user_session#new", :as => 'login'
  post "login" => "user_session#create", :as => 'login'
  delete "logout" => "user_session#destroy", :as => 'logout'

  get "user/new" => "user#new", :as => 'signup'
  post "user/new" => "user#create", :as => 'signup'
  match "user/:id/edit" => "user#edit", :via => 'get', :as => 'edit_account'
  match "user/:id" => "user#destroy", :via => 'delete', :as => 'user_delete'
  match "user/:id" => "user#update", :via => 'put', :as => 'user'
  match "user" => "user#index", :via => 'get', :as => 'user_index'

  get "export" => "application#export_bundle"

  root :to => 'messages#index', :via => 'get', :lang => 'en_US'

end

app/views/page/edit.html.erb
<h1>Edit page <code><%= @page.name %></code></h1>

<% form_for(@page, :url => page_update_url, :html => { :method => :put}) do |f| %>
  <%= f.text_area :content, :size => '100x30', :disabled => @is_default_locale %>
  <%= f.hidden_field :name, :value => @page.name %>
  <br/>
  <%= f.submit unless @is_default_locale%>
<% end %>

app/views/page/index.html.erb
<h1>ActiveInbox Help pages </h1>
<ul>
  <% @pages.each do |page_name, page| %>
    <% classes = []; classes.push( page.in_sync ? 'in_sync' : 'not_in_sync'); classes.push('translated') if page.locale.lang_code === @locale.lang_code %>
    <li class="<%= classes.join(' ') %>"><%= link_to(page.name, page_form_url(:lang => @locale.lang_code, :id => page.id)) %></li>
  <% end %>
</ul>