config/routes.rb
ActiveInboxTranslator::Application.routes.draw do

  match 'messages/:lang' => 'messages#create', :via => 'post', :as => 'messages'
  match 'messages/:lang/:id' => 'messages#update', :via => 'put', :as => 'messages'
  match 'messages(/:lang)' => 'messages#index', :via => 'get', :as => 'messages'

  match 'pages/:lang/:id/edit' => 'page#edit', :via => 'get', :as => 'page_form'
  match 'pages/:lang/:id' => 'page#update', :via => 'put', :as => 'page_update'
  match 'pages(/:lang)' => 'page#index', :via => 'get', :as => 'pages'

  get "login" => "user_session#new", :as => 'login'
  post "login" => "user_session#create", :as => 'login'
  delete "logout" => "user_session#destroy", :as => 'logout'

  get "user/new" => "user#new", :as => 'signup'
  post "user/new" => "user#create", :as => 'signup'
  match "user/:id/edit" => "user#edit", :via => 'get', :as => 'edit_account'
  match "user/:id" => "user#destroy", :via => 'delete', :as => 'user_delete'
  match "user/:id" => "user#update", :via => 'put', :as => 'user'
  match "user" => "user#index", :via => 'get', :as => 'user_index'

  get "export" => "application#export_bundle"

  root :to => 'messages#index', :via => 'get', :lang => 'en_US'

end

app/views/layouts/_header.html.erb
<% user =  current_user %>
<div id=user-menu>
  <% if user %>
    Logged in as <%= link_to(user.email, edit_account_url(:id => user.id)) %> | 
    <% if user.is_admin %>
      <%= link_to(" Manage users", user_index_url) %> |
      <%= link_to(" Export", export_url) %> |
    <% end %>
    <%= link_to "logout", logout_url, :method => :delete %>
  <% end %>
</div>

<% if flash[:notice] %>
  <p class=notice><%= flash[:notice] %></p>
<% end %>

<%= render 'layouts/page-message-tab' if %w[messages page].include?(params[:controller]) %>

app/views/layouts/_locale-menu.html.erb
<ul class=locale-menu>
  <% for locale in locales
    # link to locale page listings if the current controller is page, otherwise link to message lists.
    active_path = Proc.new {|args| params[:controller] === 'page' ? pages_url(args) : messages_url(args) } 
    active_class = params[:lang] === locale.lang_code ? 'class=active' : ''
    anchor = link_to(locale.lang_code, active_path.call( :lang => locale.lang_code) )
    # get locale stats
    pp master_count
    stats = Message.translation_stats(locale, master_count)
  %>
  <li <%=active_class%> data-percentage=<%=stats[:percentage]%> data-completeness=<%=stats[:status]%>><%=anchor%></li>
  <% end %>
</ul>

app/views/layouts/_page-message-tab.html.erb
<ul class=page-message-tab>
  <%
    lang_code = (params.has_key?(:lang) and params[:lang]) ? params[:lang] : Rails.configuration.gtdinbox_master_locale.lang_code
  %>
  <li <%= "class=active" if params[:controller] === 'messages' %>><%= link_to("messages", messages_url(:lang => lang_code)) %></li>
  <li <%= "class=active" if params[:controller] === 'page' %>><%= link_to("pages", pages_url(:lang => lang_code)) %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ActiveInboxTranslator</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
 <div id=wrapper>
  <%= render :partial => 'layouts/locale-menu', :locals => {
    :locales => locale_menu,
    :master_count => master_locale_count
  } %>

  <%= render 'layouts/header' %>
  <div id=main>
    <%= yield %>
  </div>
</div>

</body>
</html>